### ISSUE TITLE
ResultIterator::isLast should return true on empty Model/CollectionIterator

### ISSUE THREAD

**Issue by ishenkoyv** [pomm-project/Foundation#60]
I think if collection doesn't contain any elements ResultIterator should return true on isLast method call. Currently

```
$this->collection->count() -> 0
$this->collection->isLast() -> false
```

What do you think?

**Comment by chanmix51** [comment]
I am not sure I do agree with that. `isFirst()` and `isLast()` methods do provide informations for the current record of a collection. If no records are returned, `isLast()` could not either be true nor false imho since a non existent record cannot be the last and cannot be not the last. I'd say these methods should then return NULL (unknown). 

Any more thoughts ?

**Comment by ishenkoyv** [comment]
I agree. NULL is more appropriate method result for empty collection and php handle it as false on logic operations.
Would you like I make pull request?

**Comment by chanmix51** [comment]
We have to be careful not to introduce regressions on existing applications.

**Comment by chanmix51** [comment]
The fix has been committed in a separate branch to let people test and adapt their code before it gets into master.
